### ISSUE TITLE
Unable to install with pipenv

### ISSUE THREAD

**Issue by ruslaniv** [femtotrader/python-eodhistoricaldata#5]
Running 
`pipenv install git+https://github.com/femtotrader/python-eodhistoricaldata.git`

results in 

```
Installing git+https://github.com/femtotrader/python-eodhistoricaldata.git...
✘ Installation Failed 
```

**Comment by deios0** [comment]
What's exact error do you have?

**Comment by ruslaniv** [comment]
For some reason PyCharm was cutting off the actual error message. 
But running it in iTerm, revealed the error:
```
WARNING: pipenv requires an #egg fragment for version controlled dependencies. 
Please install remote dependency in the form git+https://github.com/femtotrader/python-eodhistoricaldata.git#egg=<package-name>.
```
So I was able to install the package with :
`pipenv install git+https://github.com/femtotrader/python-eodhistoricaldata.git#egg=python-eodhistoricaldata`
